# Generated by Django 5.1.15 on 2026-09-09 06:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_workspace_agent_autonomy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task', models.CharField(choices=[('inbox', 'Inbox'), ('calendar', 'Calendar'), ('digest', 'Digest'), ('command', 'Command')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('dry_run', models.BooleanField(default=False)),
                ('instruction', models.TextField(blank=True, default='', help_text="The human's request (command runs only).")),
                ('report', models.JSONField(blank=True, default=dict, help_text="The agent's structured RunReport.")),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'autopilot_agent_run',
                'ordering': ['-created_at'],
            },
        ),
    ]
