# Generated by Django 5.1.15 on 2026-09-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0017_seed_missing_analytics_platform_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='auth_source',
            field=models.CharField(choices=[('own', 'Own developer app'), ('composio', 'Composio')], default='own', max_length=20),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='composio_connected_account_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
