# Generated by Django 5.1.15 on 2026-09-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_alter_workspace_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='agent_autonomy',
            field=models.CharField(choices=[('off', 'Off'), ('draft_only', 'Draft only'), ('autopilot', 'Autopilot')], default='draft_only', max_length=20),
        ),
    ]
