# Generated by Django 5.1.15 on 2026-09-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('post_submitted', 'Post submitted for approval'), ('post_approved', 'Post approved'), ('post_changes_requested', 'Post changes requested'), ('post_rejected', 'Post rejected'), ('post_published', 'Post published'), ('post_failed', 'Post failed'), ('new_inbox_message', 'New inbox message'), ('inbox_sla_overdue', 'Inbox SLA overdue'), ('client_approval_requested', 'Client approval requested'), ('team_member_invited', 'Team member invited'), ('social_account_disconnected', 'Social account disconnected'), ('report_generated', 'Report generated'), ('engagement_alert', 'Engagement alert'), ('comment_mention', 'Mentioned in a comment'), ('approval_reminder', 'Approval reminder'), ('approval_stalled', 'Stalled approval escalation'), ('approval_hold_requested', 'Client requested a hold'), ('client_connected_accounts', 'Client connected accounts'), ('agent_decision_needed', 'Osir AI agent needs a decision'), ('agent_digest', 'Osir AI agent digest')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=[('post_submitted', 'Post submitted for approval'), ('post_approved', 'Post approved'), ('post_changes_requested', 'Post changes requested'), ('post_rejected', 'Post rejected'), ('post_published', 'Post published'), ('post_failed', 'Post failed'), ('new_inbox_message', 'New inbox message'), ('inbox_sla_overdue', 'Inbox SLA overdue'), ('client_approval_requested', 'Client approval requested'), ('team_member_invited', 'Team member invited'), ('social_account_disconnected', 'Social account disconnected'), ('report_generated', 'Report generated'), ('engagement_alert', 'Engagement alert'), ('comment_mention', 'Mentioned in a comment'), ('approval_reminder', 'Approval reminder'), ('approval_stalled', 'Stalled approval escalation'), ('approval_hold_requested', 'Client requested a hold'), ('client_connected_accounts', 'Client connected accounts'), ('agent_decision_needed', 'Osir AI agent needs a decision'), ('agent_digest', 'Osir AI agent digest')], max_length=50),
        ),
    ]
